content/guides/recipes/docker-logging.md

Fix a typo

---

views/download.erb

I fixed a broken link of fluent-bit.

fix a link to download instruction of fluent-bit

---

scripts/obsolete-plugins.yml

* fluent-plugin-wineventlog
* fluent-plugin-encrypt
* fluent-plugin-dummdata-producer
* fluent-plugin-bigquery-patched-retry-insert-502
* fluent-plugin-access

Mark some plugins as obsolete

---

scripts/obsolete-plugins.yml

Use fluent-plugin-twilio instead.

Boundio has already closed on 2013-09-30

---

scripts/obsolete-plugins.yml

* fluent-plugin-gcs-dustinblackman
* fluent-plugin-gcloud-storage

Add obsoleted plugins for Google Cloud Storage Service

---

content/guides/recipes/docker-logging.md

Fix kubernetes logging broken link

---

views/videos.erb

Fixed broken link

---

views/guides.erb

**Fix: #65** 
Signed-off-by: Shivesh Abhishek <shivesh.abhishek@mayadata.io>

Fix URL to 'Logging Docker Container Logs'

---

scripts/obsolete-plugins.yml

Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>

Mark fluent-plugin-logzio-ng as obsoleted

---

tmpl-assets/css/pages/page_404_error.css
tmpl-assets/css/pages/page_404_error1.css
tmpl-assets/css/style.css
tmpl/Documentation/css/docs.css
tmpl/HTML/assets/css/pages/page_404_error.css
tmpl/HTML/assets/css/pages/page_404_error1.css
tmpl/HTML/assets/css/style.css
views/layout.erb

http -> https (rebase #41)

---

content/blog/20181110_fluentd-v1.3.0-has-been-released.md

Hi. I've created a small patch for v1.3.0 announcement.
Because several users have requested this feature in https://github.com/fluent/fluentd/issues/1701,
I think it's probably worth mentioning in the announcement too.
Signed-off-by: Fujimoto Seiji <fujimoto@clear-code.com>

Add mention of the CORS improvement to the blog post

---

content/casestudy/hellofresh.md

To describe the case of HelloFresh

HelloFresh case study

---

views/faqs.erb

- Fix broken package install doc links.
- Add links for Ruby gems and source code installs and for MSI package
installs.

Update documentation links.

---

Gemfile

These releases ships some security fixes.
https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-6-4-released/
https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-6-5-released/
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-6-6-released/

Update supported Ruby runtime on Heroku

---

assets/css/style.css

Apply patch from the following PR by @okkez.
https://github.com/fluent/fluentd-website/pull/78/commits/44c6a2dbed77966bbcf06b0f3235862384b51d1b

Remove garbage right parenthesis

---

views/layout.erb

Salvaged from the past PR.
https://github.com/fluent/fluentd-website/pull/78/commits/33b82f5db02d0b136e83a5771cc4e9f836925fdd

Fix layout indentation

---

Gemfile
Gemfile.lock
app.rb

This reverts commit 726f0601c3fec5785ba256a4842dd4c5e690a835.
It seems cause crash.

Revert "Switch from yui-compressor to sassc,uglifier"

---

views/layout.erb

Fix missing fluentd logo

---

views/download.erb

Add missing comma in download page

---

app.rb

Signed-off-by: Hisa Tanaka htanaka@ctc-america.com

Adding an author to post a blog about the fluentcon summary

---

content/blog/20210504_fluentcon-recap.md

Signed-off-by: Hisa Tanaka <htanaka@ctc-america.com>

Blog to recap the 1st FluentCon

---

views/_right_menu.erb
views/layout.erb
views/related_projects.erb

This should be becoming a vulnerbility to invite users into a phishing page.
We shouldn't trust 3rd party page.
ref: https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>

Prevent Tab Nabbing

---

content/blog/20210526_fluentd-v1.12.4-has-been-released.md

v1.12.4 announcement is missing

blog:v1.12.4 release announcement

---

views/index.erb

Set the maximum width for the picture

fix: The picture will exceed the width of the screen on mobile

---

.circleci/config.yml
Gemfile
Gemfile.lock

https://devcenter.heroku.com/articles/ruby-support#supported-runtimes

Use Ruby 2.6.8

---

content/blog/20210929_fluentd-v1.14.1-has-been-released.md

blog: add v1.14.1 release announcement

---

app.rb
content/blog/20211213_td-agent-v4.3.0-has-been-released.md
views/download.erb

* Update download links
* Post a blog article for it

Update td-agent to 4.3.0

---

.circleci/config.yml
Gemfile.lock

circleci: Use Ruby 2.7.5

---

views/architecture.erb

Fix a broken link

---

assets/plugins/back-to-top.js
views/index.erb
views/layout.erb

resolve https://github.com/fluent/fluentd-website/issues/187

Accessibility add alt to img

---

views/index.erb
views/layout.erb

resolve https://github.com/fluent/fluentd-website/issues/189

Accessibility add iframe title

---

views/layout.erb

resolve https://github.com/fluent/fluentd-website/issues/192
cc @ashie

Accessibility add link name (social)

---

views/layout.erb

resolve https://github.com/fluent/fluentd-website/issues/196

update social list

---

views/blog.erb

resolve https://github.com/fluent/fluentd-website/issues/200

Accessibility add link name

---

views/architecture.erb

resolve https://github.com/fluent/fluentd-website/issues/205

Accessibility add alt to images

---

views/why.erb

resolve https://github.com/fluent/fluentd-website/issues/210

Accessibility add alt to images (why page)

---

assets/css/responsive.css

resolve https://github.com/fluent/fluentd-website/issues/203

fix iframe video for mobile

---

views/datasources.erb

resolve https://github.com/fluent/fluentd-website/issues/212

Accessibility add alt to datasources page

---

views/dataoutputs.erb

resolve https://github.com/fluent/fluentd-website/issues/214

Accessibility add alt dataoutputs page

---

views/index.erb

resolve https://github.com/fluent/fluentd-website/issues/194

Accessibility add logos name

---

assets/css/responsive.css

resolve https://github.com/fluent/fluentd-website/issues/217

add responsive table

---

app.rb
content/blog/20220628_td-agent-v4.3.2-has-been-released.md

Release announce of td-agent v4.3.2

---

views/download.erb

I fixed for trailing ">" and adding h4 table title for Td-Agent.

Style fixing for download page

---

views/download.erb

Fix name of td-agent

---

content/blog/20220729_fluentd-v1.15.1-has-been-released.md

CHANGELOG: https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1151---20220727

blog: Add v1.15.1 release announcement

---

app.rb
content/blog/20220823_td-agent-v4.4.1-has-been-released.md

Release announce of td-agent v4.4.1

---

app.rb

scripts/plugins.json is updated directly by GitHub Actions: #237

No longer use tmp/plugins.json

---

content/testimonials.yaml
views/related_projects.erb

Signed-off-by: Adithya Krishna <adikrish@redhat.com>

[Bug]- Fixed Broken Links

---

views/layout.erb

- Closes #234
/cc @caniszczyk @edsiper

Add CNCF GA4 site tag

---

views/enterprise_services.erb

Fix URL of ClearCode's service page

---

content/blog/20230329_fluentd-v1.16.0-has-been-released.md

* https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1160---20230329
* https://github.com/fluent/fluentd/releases/tag/v1.16.0

blog: Add v1.16.0 release anouncement

---

content/blog/20230420_fluentd-v1.16.1-has-been-released.md

* https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1161---20230417
* https://github.com/fluent/fluentd/releases/tag/v1.16.1

blog: Add v1.16.1 release anouncement

---

scripts/plugins.rb

The size of plugins.json will be shrinked.
Before: about ~ 1.2MB
After: about ~ 284KB

Shrink plugins.json by collecting required attributes

---

views/index.erb

updated survey link to use a custom link for this site, which will allow us to determine the best resources for getting people to take the survey
Signed-off-by: Erik Bledsoe <erik@calyptia.com>

update survey link

---

app.rb
views/download.erb
views/download_fluent_package.erb

This is followup of #268 
/download/td_agent will be redirected to /download/fluent_package

Add fluent-package download entries

---

content/blog/tag/announcement
content/blog/tag/fluent-package
content/blog/tag/fluentbit
content/blog/tag/fluentd
content/blog/tag/observability
content/blog/tag/td-agent

$ bundle exec ruby scripts/generate_tags.rb

Update tags for recent blog articles

---

.github/workflows/update-plugins.yaml
scripts/plugins.rb

Before:
Update plugin.json
After:
Update plugins.json
added plugins:
* fluent-plugin-foo
deleted plugins:
* fluent-plugin-bar

Add more explanation to commit message

---

content/blog/20231114_fluentd-v1.16.2-v1.16.3-have-been-released.md

* https://github.com/fluent/fluentd/blob/v1.16/CHANGELOG.md#release-v1163---20231114
* https://github.com/fluent/fluentd/releases/tag/v1.16.3

blog: Add v1.16.3 and v1.16.2 release anouncement

---

content/blog/20231204_ossjapan-2023.md

Fluentd maintainers Daijiro Fukuda and Kentaro Hayashi will talk about Fluentd in OSS Japan 2023!

blog: Add ossjapan-2023 blog

---

content/blog/20231204_ossjapan-2023.md

blog: change to meaningful blog title

---

app.rb

https://www.fluentd.org/download should be updated.

Bump version to v5.0.3

---

content/blog/tag/announcement
content/blog/tag/event
content/blog/tag/fluent-package
content/blog/tag/fluentd
content/blog/tag/opensource

$ ruby scripts/generate_tags.rb

Update blog content tags

---

content/blog/20240329_fluent-package-v5.0.3-has-been-released.md

From https://github.com/fluent/fluentd/discussions/4552
https://www.fluentd.org/blog/fluent-package-v5.0.3-has-been-released

blog: fix link

---

content/blog/20240702_fluent-package-v5.0.4-has-been-released.md

This is the same fix with:
https://github.com/fluent/fluentd-website/pull/316

blog: fix broken link again

---

content/blog/20240819_fluentd-v1.17.1-has-been-released.md

blog: fix a typo

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yml

It formalize feedback from users.

github: add issue template

---

views/enterprise_services.erb

Fix the broken grid of https://www.fluentd.org/enterprise_services.
We should use Bootstrap appropriately to fix the broken grid.
Before:
After:
(The font differences are due to my local environment.)

enterprise-services: fix broken grid

---

views/faqs.erb

There are some obsolete content in https://www.fluentd.org/faqs, so let's update it.

Update obsolete explanation

---

views/faqs.erb

Some differences are not important for users anymore. We should remove them for clarity.
https://www.fluentd.org/faqs
Before:
After:

faqs: remove unnecessary differences

---

views/download_fluent_package.erb

https://www.fluentd.org/download/fluent_package

download-fluent-package: update links for installation guides

---

views/download_calyptia_fluentd.erb

https://www.fluentd.org/download/calyptia_fluentd

download-calyptia-fluentd: update links for installation guides

---

.github/ISSUE_TEMPLATE/testimonials.yml

Navigate from fluent/fluentd issue template to collect Fluentd use-case.

github: add form to collect user use-case/testimonials

---

.github/ISSUE_TEMPLATE/testimonials.yml

* fill default issue title by default
* tweak to input field
* fill in placeholder
* explain how field is used in testimonials
followup #352

github: tweak feedback issue template

---

views/blog_single.erb

Apply each blog entry to be notified

blog: insert feedback for Use-Case/Testimonials

---

content/blog/20250501_fluentd-v1.16.8-has-been-released.md

This PR will fix typo in link syntax at https://github.com/fluent/fluentd-website/pull/371

blog: fix link syntax

---

content/blog/20250514_fluentd-v1.16.9-has-been-released.md
content/blog/tag/announcement
content/blog/tag/fluent-package
content/blog/tag/fluentd

https://github.com/fluent/fluentd/blob/v1.16/CHANGELOG.md#release-v1169---20250514
https://github.com/fluent/fluentd/releases/tag/v1.16.9

blog: add fluentd v1.16.9 release announcement

---

content/blog/20241214_fluent-package-v5.2.0-has-been-released.md

https://www.fluentd.org/blog/fluent-package-v5.2.0-has-been-released

blog: fix wrong explanation about zero-downtime update

---

.github/ISSUE_TEMPLATE/testimonials.yml

We use only .png format in views/testimonials.erb

testimonials: explicitly describe PNG is preferred

---

content/blog/20250904_upgrade-guide-for-fluent-package-v6.md

https://www.fluentd.org/blog/upgrade-guide-for-fluent-package-v6

blog: fix upgrade guide for fluent-package v6
