content/datasources/flume-ng.md, content/datasources/flume.md
And add note in Flume-Legacy page.
Related to #6.
It would be nice to have `Flume-NG` descriptions page in Fluentd website.
=> flume-ng: Add flume-ng datasource description page

app.rb, views/download.erb
Now, we can get a td-agent-bit v0.9.
(e.g td-agent-bit-0.9.0-1.x86_64, via yum)
So, I bumped 0.8.5 -> 0.9.0.
=> bump version of td-agent-bit to 0.9.0

scripts/plugins.rb
Because it has been maintained since 2015-10-08 or earlier.
See https://github.com/yuku-t/fluent-plugin-mysqlslowquery/issues/15#issuecomment-146473679
=> Add fluent-plugin-mysqlslowquery to obsolete plugins

scripts/plugins.rb
Because in_tail_path had been merged in in_tail in v0.12.
ref: https://github.com/fluent/fluentd/issues/945
ref: https://github.com/fluent/fluentd/pull/951
~~Please merge this PR after Fluentd reaches v0.14.x as stable.~~
I've confirmed that in_tail_path is also merged into v0.12.
=> Add fluent-plugin-tail_path to obsoleted plugins

scripts/plugins.rb
* It has not been maintained since 2 years ago
* fluent-plugin-amqp has been maintained actively
* It has both output plugin and input pluguin
* Support v0.14 API
=> Add fluent-plugin-amqp2 to obsolete plugins

scripts/obsolete-plugins.yml
Because bundled in_tail is enough.
=> Add fluent-plugin-tail-multiline-ex to obsolete plugins

scripts/obsolete-plugins.yml
Because original author has made this package deprecated.
See https://github.com/blend/fluent-plugin-cloudtrail
=> Mark obsolete fluent-plugin-cloudtrail

scripts/obsolete-plugins.yml
* fluent-plugin-bigquery-custom
Owner said: Almost feature is included in original. Use
fluent-plugin-bigquery instead.
* fluent-plugin-embedded-elasticsearch
Git repository has gone away.
=> Update obsolete plugins

scripts/obsolete-plugins.yml
Because [Kestrel](https://github.com/robey/kestrel) is inactive and
unmaintained since 2014-03-07.
=> Mark obsolete fluent-plugin-kestrel

scripts/obsolete-plugins.yml
Because it has been replaced with Droonga engine.
=> Mark fluent-plugin-droonga obsolete

scripts/obsolete-plugins.yml
This plugin is obsolete because HAPI1 is deprecated.
=> Mark fluent-plugin-hatohol is obsolete

scripts/obsolete-plugins.yml
Because Growl does not support OS X 10.10 or later.
And 10.10 encourages to use notification center.
=> Mark fluent-plugin-growl is obsolete

scripts/obsolete-plugins.yml
Because already merged into upstream.
=> Mark fluent-plugin-norikra-patched-7 is obsolete

scripts/obsolete-plugins.yml
Obsoleted Reasons:
* Depends on Fluentd v0.10
* It causes installation error when users use Ruby 2.4
* Unmaintained since 30 Sep 2014
* I sometimes send ping, but no response from maintainer
* fluent-plugin-dynamodb has almost same functionality
=> Mark fluent-plugin-ynamodb-drc as obsoleted

scripts/obsolete-plugins.yml
fluent-plugin-redshit had already used aws-sdk-v1 explicitly.
=> Mark fluent-plugin-redshift-aws-v1 as obsoleted

scripts/obsolete-plugins.yml
* These plugins are modified gem name only, but almost feature is included in original.
=> Mark fluent-plugin-redshift-kwarter and fluent-plugin-hekk_redshift as obsoleted plugin

scripts/obsolete-plugins.yml
Because SSL verify feature is included in original.
=> Mark fluent-plugin-elasticsearch-ssl-verify as obsoleted

app.rb
How about adding slack entry for plugin page?
https://www.fluentd.org/plugins#notifications
Because Slack plugin is most downloaded major notification plugin.
And I confirmed that also have a entry of slack in `scripts/plugins.json`
=> Add slack for Notification plugin category

scripts/obsolete-plugins.yml
> NOTE: grep filter is now a built-in plugin. Use the built-in plugin instead of installing this plugin.
> Or, you may find https://github.com/sonots/fluent-plugin-filter_where is more useful.
see: https://github.com/sonots/fluent-plugin-grep
=> Mark fluent-plugin-grep as deprecated

scripts/obsolete-plugins.yml
fluent-plugin-kv-parser is replaced with built-in parser_ltsv, because
parser_ltsv provides all feature of fluent-plugin-kv-parser.
fluent-plugin-lvsv-parser is replaced with build-in parser_ltsv,
because fluent-plugin-ltsv-parser has benn unmaintained since
2014-10-29, and built-in parser_ltsv provides the feature to parse LTSV.
fluent-plugin-json-parser is replaced with built-in parser_json,
because fluent-plugin-json-parser has benn unmaintained since
2014-08-19, and built-in parser_json provides the feature to parse JSON.
=> Some parser plugins are replaced with built-in plugin

scripts/obsolete-plugins.yml
fluent-plugin-kanicounter doesn't include any practical functionalities.
=> Mark fluent-plugin-kanicounter as obsoleted

scripts/obsolete-plugins.yml
built-in stdout can buffer events.
fluent-plugin-hipchat can also buffer events.
=> Mark fluent-plugin-stdout and fluent-plugin-buffered-hipchat obsoleted

scripts/plugins.rb
`gem search -r fluent-plugin` includes following gems:
* ivelum-fluent-plugin-oomkiller
* roched-fluent-plugin-kafka
* sm-fluent-plugin-sql
* vmik-fluent-plugin-google-cloud
`cmdout.scan(/fluent-plugin-[^\s]+/)` will return followings:
* fluent-plugin-oomkiller
* fluent-plugin-kafka
* fluent-plugin-sql
* fluent-plugin-google-cloud
So we see duplicated entries in https://www.fluentd.org/plugins/all
This change omit username-prefixed gems on the above.
=> Stop storing duplicated gems

content/guides/recipes/docker-logging.md
Simple typo fixes that I discovered when reading the docs for fluentd and docker logging.
=> Fix typos in docker-logging.md

scripts/obsolete-plugins.yml
Because its repository has gone away.
Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>
=> Mark fluent-plugin-filter-geo as obsoleted

scripts/test_5xx.rb
These tests will fail when we forget re-generating tags after we add
new tags.
=> Add test for almost contents

views/download.erb
While updating the Graylog article in https://github.com/fluent/fluentd-docs/pull/587, I noticed
that the download link for the latest Ubuntu version was missing. 
This patch contains a trivial fix for the issue.
Signed-off-by: Fujimoto Seiji <fujimoto@clear-code.com>
=> Add download links for Ubuntu 18.04 (Bionic Beaver)

scripts/obsolete-plugins.yml
Upstream plugin, which is fluent-plugin-out-http, supports full downstream plugin functionality. It can be replaceable now.
=> Mark fluent-plugin-out-http-ext as obsoleted

views/dataoutputs.erb
The "List of Outputs" page shows wrong logo icon for OpenTSDB
(displaying the one for HBase). 
This patch resolves the issue and should fix #72 
Signed-off-by: Fujimoto Seiji <fujimoto@clear-code.com>
=> Show the correct icon for OpenTSDB

app.rb
Some links of tags are broken.
https://www.fluentd.org/blog/tag/ui returns "Internal server error".
See https://www.fluentd.org/blog/fluentd-admin-ui
=> Fix blog tags

content/blog/20190402_fluentd-v1.4.2-has-been-released.md
This is the release note for `v1.4.2`.
Update the article title so that it references the correct version number.
=> blog: fix the title of the v1.4.2 release note

views/download.erb
The Gem and macOS Installation Guide links are currently dead
=> Fixing Installation Guide links on download page

views/download.erb
Even though Debian Buster is  listed in https://docs.fluentd.org/installation/install-by-deb but not for https://www.fluentd.org/download.
=> Add missing Buster download link

views/layout.erb
The following patch changes the Google Analayts Tag scripts from
the one used by Treasure Data to CNCF.
Since we don't find a way to transfer the GA account to CNCF, it's
easier to just setup a new one.
note: the scripts on this patch are provided by CNCF
Signed-off-by: Eduardo Silva <eduardo@treasure-data.com>
=> ga: switch Google Analytics Tag from TD to CNCF

app.rb, content/blog/20210218_fluentd-v1.12.1-has-been-released.md
This adds a news blog post for Fluentd v1.12.1 which was released
February 18, 2021.
This also updates the latest version of TD Agent to v4.1.0, so that
[the release page](https://www.fluentd.org/download
) is kept updated.
Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>
=> Add a public release for Fluentd v1.12.1

app.rb
We've uploaded the td-agent-4.1.0-x64.msi: https://td-agent-package-browser.herokuapp.com/4/windows
=> Update td-agent for Windows to 4.1.0

.circleci/config.yml
Because deploying is broken as of #117
https://app.circleci.com/pipelines/github/fluent/fluentd-website/72/workflows/453fc419-d539-45fa-83fe-0f736d7e144b/jobs/549
=> circleci: Upgrade to Ruby 2.6.6

Gemfile.lock
PR #117 lacks updadating Gemfile.lock
=> Update to Ruby 2.6.6 again

Gemfile, Gemfile.lock, app.rb
As yui-compressor is not maintained anymore [1], so
it should migrate from it.
The past PR [2] tried to migrate to sass and uglifier, but now sass is
also deprecated. so sassc and uglifier are the reasonable choice for
migration.
[1] https://rubygems.org/gems/yui-compressor
[2] https://github.com/fluent/fluentd-website/pull/78/commits/71f175814fd902fd5d4c2dc151b0e66e2d84c540
[3] https://sass-lang.com/ruby-sass
Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>
=> Switch from yui-compressor to sassc,uglifier

views/_right_menu.erb, views/community.erb, views/contributing.erb, views/layout.erb
We are migrating Forum / Mailing List to Discourse.
We will deprecate Google Groups (https://groups.google.com/group/fluentd).
See also: https://groups.google.com/g/fluentd/c/z6e4ziIfzdo
=> Add links to https://discuss.fluentd.org/

Gemfile, Gemfile.lock, app.rb
As yui-compressor is not maintained anymore [1], so
it should migrate from it.
The past PR [2] tried to migrate to sass and uglifier, but now sass is
also deprecated. so sassc and uglifier are the reasonable choice for
migration.
[1] https://rubygems.org/gems/yui-compressor
[2] https://github.com/fluent/fluentd-website/pull/78/commits/71f175814fd902fd5d4c2dc151b0e66e2d84c540
[3] https://sass-lang.com/ruby-sass
In the previous migration PR, https://github.com/fluent/fluentd-website/pull/125
set :assets_css_compressor should be :sass instead of :sassc.
Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>
=> Switch from yui-compressor to sassc,uglifier again

.circleci/config.yml
Currently the master branch on Heroku is conflicting with GitHub's one.
https://app.circleci.com/pipelines/github/fluent/fluentd-website/85/workflows/49151be9-989f-4ec3-ab16-00617ad6fed5/jobs/575
```
To https://git.heroku.com/******************.git
! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://heroku:************************************@git.heroku.com/******************.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
It should be …
=> circleci: Force push the git repository to Heroku

Gemfile, Gemfile.lock, Procfile, config.ru, config/puma.rb
Puma is Now the Recommended Ruby Webserver
https://devcenter.heroku.com/changelog-items/594
Since January 2015, Puma is recommended web server
on Heroku.
=> Migrate to Puma application server

app.rb, views/download.erb
In addition, add some missing links
* RPMs for aarch64
* Aamazon Linux 2
* td-agent 4 macOS package
=> Update td-agent to 4.1.1

.circleci/config.yml, Gemfile, Gemfile.lock
Ruby 2.6.7 is also available on heroku
https://devcenter.heroku.com/changelog-items/2087
Ruby 2.6.7 is available on CircleCI
https://circleci.com/docs/2.0/circleci-images/#ruby
=> Upgrade to Ruby 2.6.7

views/contributing.erb
We migrated it from omnibus-td-agent to fluent-package-builder:
* Before: https://github.com/treasure-data/omnibus-td-agent/
* After:  https://github.com/fluent-plugins-nursery/fluent-package-builder
=> Replace a link for td-agent issue tracker

views/blog_single.erb
fluentd-blog.disqus.com is not managed by Fluentd team
and it seems that no one owns admin privilege.
This situation is not welcoming status, so drop it.
The following area will be  dropped from each blog entry.
=> Drop Disqus integration

views/blog.erb, views/blog_single.erb, views/layout.erb
This link leads to the following announcemenet page:
In December 2018, we announced our decision to shut down
Google+ for consumers in April 2019.
So these Google+ links are not being workign since 2 years ago
at least. Remove them.
Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>
=> Remove Google+ links from the website

content/blog/draft_fluentd-v1.14.5-has-been-released.md
Add a draft of v1.14.5 release announcement.
=> blog: v1.14.5 release announcement

content/blog/20210529_fluentd-v1.13.0-has-been-released.md, content/blog/20210625_fluentd-v1.13.1-has-been-released.md, content/blog/20210712_fluentd-v1.13.2-has-been-released.md, content/blog/20210727_fluentd-v1.13.3-has-been-released.md, content/blog/20210830_fluentd-v1.14.0-has-been-released.md, content/blog/20210929_fluentd-v1.14.1-has-been-released.md, content/blog/20211029_fluentd-v1.14.2-has-been-released.md, content/blog/20211126_fluentd-v1.14.3-has-been-released.md, content/blog/20220106_fluentd-v1.14.4-has-been-released.md, content/blog/20220209_fluentd-v1.14.5-has-been-released.md
Recently, it was found that the heading style in CHANGELOG.md was unexpectedly changed.
It has been fixed with https://github.com/fluent/fluentd/pull/3648.
Then blog entries that contain links to CHANGELOG.md should be also updated.
=> Follow updated CHANGELOG.md heading styles

Gemfile, Gemfile.lock
2.6.x will reach EOL at March, 2022.
It seems okay with % git push heroku master.
=> Update Ruby to 2.7.5

app.rb, views/download.erb
In addition, fix wrong version number for Windows.
=> Add RHEL9 and Ubuntu Jammy to download page

views/download.erb
* Use list to to make easy to recognize 2 major distributions
* Add anchors to make eaty to link to each distributions
* Separate td-agent and community distributions
* Docker images, Kubernetes DaemonSet and Ruby gems aren't td-agent!
* Uncomment Kubernetes DaemonSet for Fluentd v1
* Although I'm not sure why it's commented out, it should be visible since it's one of major distribution of Fluent nowadays.
* Replace `v1.0` with `v1` for Fluentd's feature version
* All v1.x keep backward compatibility, so `v1.0` is inappropriate
* Fix typo (kuberetes -> kubernetes)
=> Reformat download page

.circleci/config.yml, Gemfile, Gemfile.lock, Rakefile, app.rb, config/puma.rb
* Dependent gems are also updated
* Remove shotgun because it doesn't support Ruby 3
* Use latest version of shinatra-asset-pipeline in GitHub to resolve conflict of required rake version
* To make sure to exist the specified revision, use our fork repository
* Replace `File.exists?` with `File.exist?`
* Remove jemalloc gem because it doesn't seem used in actual and it uses `File.exists?`
=> Update Ruby to v3.2.2

scripts/plugins.rb
Another approach #269 
Before:
* Update plugins.json every day
After:
* Update plugins.json when the number of plugin is changed.
* Reduce commit just update "downloads" field. Note that "downloads" may be inaccurate.
=> Reduce frequency to update plugins.json

.github/workflows/update-plugins.yaml
checkout@v2 uses deprecated node12.
=> github: upgrade to checkout@v3

scripts/plugins.rb
This is followup of  #276
Before:
loading plugins.json depends on executing context
After:
always specify path of scripts/plugins.json correctly
=> Do not rely on relative path

app.rb
Currently, "Recent Posts" entry is limited to 5 articles. It may be a bit small count of entries to track in sidebar. (As no further tracking method from /blog/ for old entries.)
=> Show more blog articles in "Recent Posts"

.github/workflows/update-plugins.yaml
Without this, scripts/plugins.rb can't check the last commit date of plugins.json correctly on GitHub Actions.
=> GHA: Specify fetch-depth for actions/checkout to get history of plugins.json

app.rb
We don't post blog article for it not to diturb fluent-package v5 release announcement.
=> Update latest td-agent to v4.5.1

scripts/plugins.rb
homepage_uri is used for https://www.fluentd.org/plugins/all.
=> Add missing homepage_uri parameter

app.rb
It fixes a fatal launch failure issue due to non-ASCII registry key.
=> td-agent v4.5.3 for Windows has been released

app.rb, content/blog/20230731_upgrade-td-agent-v4-to-v5.md, content/blog/20230829_fluent-package-scheduled-lifecycle.md, content/blog/20230829_schedule-for-td-agent-4-eol.md, content/blog/tag/reminder, views/blog.erb, views/blog_single.erb
When many release article was published, major
topics will not shown in "Recent Topics".
This commit introduces "Topics" category.
=> blog: always show major topics

app.rb
When https://github.com/fluent/fluent-package-builder/pull/641 was merged and released, it should be updated.
=> Update latest version of windows msi

views/download_fluent_package.erb
Both desktop and server versions should be supported as long as the version is not out of Microsoft support.
=> Update platform version for msi fluent-package

content/blog/20240329_fluent-package-v5.0.3-has-been-released.md
https://www.fluentd.org/blog/fluent-package-v5.0.3-has-been-released
The following link is broken. (Originally, it was my file name issue. Sorry for this.)
> See [Fluentd v1.16.5 has been released](https://www.fluentd.org/blog/fluentd-v1.16.5-has-been-released) blog article about details.
This PR fixes it.
In addition, this PR adds v1.16.4 link.
after:
=> blog: fix broken link and add related link

content/blog/20240430_fluentd-v1.17.0-has-been-released.md
https://github.com/fluent/fluentd/releases/tag/v1.17.0
=> blog: Add Fluentd v1.17.0 release announcement

views/contributing.erb
Fixed the link of this page.
https://www.fluentd.org/Contributing
=> Fix Documentation's link is old

app.rb
NOTE: macOS is not supported yet.
=> Bump up fluent-package version

views/download_fluent_package.erb
Since v5.1.0, normal release channel and LTS channel ships a different version of fluent-package, so I've noticed it.
=> Fix incorrect LTS version

content/blog/20230829_schedule-for-td-agent-4-eol.md, content/blog/20240329_fluent-package-v5.0.3-has-been-released.md, content/blog/20240702_fluent-package-v5.0.4-has-been-released.md, content/blog/20240802_fluent-package-v5.1.0-has-been-released.md
It is intended to emphasize "we stopped maintaining td-agent v4".
=> blog: clarify td-agent v4 EOS explanation

views/index.erb
Fluent Bit Academy is now hosted by Chronsphere following the acquisition of Calyptia. Updating the link to its new home.
=> update Fluent Bit Academy link

content/blog/20240802_fluent-package-v5.1.0-has-been-released.md
v5.1.0 release is not a maintenance release.
=> blog: fix fluent-package v5.1.0

.github/workflows/add-to-project.yaml
It helps to track new issues by aggregating ones from Project view.
=> github: track issue with GitHub Project

views/download_fluent_package.erb
It would be enough to have v4 as the old stable.
https://www.fluentd.org/download/fluent_package
Before:
After:
=> download-fluent-package: remove td-agent v3

content/blog/20230829_fluent-package-scheduled-lifecycle.md
https://www.fluentd.org/blog/fluent-package-scheduled-lifecycle
The current table about EOL in 4.5.2 and 4.5.3 is misleading.
=> blog: add appendix for 4.5.2 and 4.5.3 about EOL of td-agent

content/blog/20250314_fluentd-drop-alpine-docker-image.md, content/blog/tag/docker, content/blog/tag/fluent-package
https://www.fluentd.org/blog/fluentd-drop-alpine-docker-image
The tags of this blog should not include `fluent-package`.
It should include `Docker` tag.
=> blog: fix tag

views/enterprise_services.erb
https://www.fluentd.org/enterprise_services
Clearcode is posting information about Fluentd in Japanese on https://x.com/fluentd_jp.
=> enterprise-services: add description

.github/workflows/check-tags.yaml
I often forget to update tags,
so this add a workflow to check for this.
This workflow run `bundle exec rake update_tags` on CI, 
and it will fail if there are any differences.
(You can see the results of the tests in https://github.com/Watson1978/fluentd-website/pull/1)
=> CI: Add workflow to check for any updates to the tag files overlooked

scripts/obsolete-plugins.yml
Note that GitHub API doesn't provide accurate
archived time in response, so just regards
last pushed_at.
See
https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository
obsolete-plugins.yml is important database for https://github.com/okkez/fluent-plugin-obsolete-plugins.
=> Mark archived plugins

app.rb, content/blog/20210504_fluentcon-recap.md, views/blog.erb, views/blog_archive.erb, views/blog_single.erb
This PR create blog achive page.
The archive page will be linked from bottom of blog page.
=> Add blog achive page
